export type RouteKey = "critical" | "general" | "protection" | "study" | "family" | "protection-access" | "eu-mobility" | "family-safety";
export type RouteFilter = "all" | "work" | "study" | "family" | "protection" | "eu";

export type Character = {
  id: string;
  name: string;
  initials: string;
  pronouns: string;
  origin: string;
  role: string;
  route: RouteKey;
  filter: Exclude<RouteFilter, "all">;
  identity: string;
  summary: string;
  stakes: string;
  tone: string;
};

export type Choice = {
  id: string;
  label: string;
  correct?: boolean;
  feedback: string;
  consequence: string;
};

export type Step = {
  stage: "Plan" | "Prepare" | "Travel" | "Arrive" | "Build a life";
  eyebrow: string;
  title: string;
  scene: string;
  question: string;
  law: string;
  plainLaw: string;
  sourceLabel: string;
  sourceUrl: string;
  choices: Choice[];
};

export const characters: Character[] = [
  {
    id: "kwame",
    name: "Kwame Mensah",
    initials: "KM",
    pronouns: "he / him",
    origin: "Ghana",
    role: "Civil engineer",
    route: "critical",
    filter: "work",
    identity: "Moving alone for a two-year engineering role",
    summary: "Kwame has an offer to work on renewable-energy infrastructure.",
    stakes: "The start date is close, and his employer assumes the job offer is enough.",
    tone: "ochre",
  },
  {
    id: "mateo",
    name: "Mateo Álvarez",
    initials: "MA",
    pronouns: "he / him",
    origin: "Argentina",
    role: "Chef",
    route: "general",
    filter: "work",
    identity: "An experienced chef planning his first move abroad",
    summary: "Mateo has found an Irish employer, but the job and offer still need to qualify.",
    stakes: "A recruiter wants a cash payment and is pressuring him to travel quickly.",
    tone: "coral",
  },
  {
    id: "farid",
    name: "Farid Rahimi",
    initials: "FR",
    pronouns: "he / him",
    origin: "Afghanistan",
    role: "Journalist",
    route: "protection",
    filter: "protection",
    identity: "Seeking safety after threats connected to his work",
    summary: "Farid cannot safely return home and wants to ask Ireland for protection.",
    stakes: "He is exhausted, has incomplete documents and is afraid he will not be believed.",
    tone: "blue",
  },
  {
    id: "priya",
    name: "Priya Nair",
    initials: "PN",
    pronouns: "she / her",
    origin: "India",
    role: "Registered nurse",
    route: "critical",
    filter: "work",
    identity: "Joining a hospital team while building a life in Ireland",
    summary: "Priya has a qualifying nursing offer and must arrange permission before travel.",
    stakes: "She needs to coordinate professional registration, immigration and a realistic move date.",
    tone: "green",
  },
  {
    id: "mariam",
    name: "Mariam Diallo",
    initials: "MD",
    pronouns: "she / her",
    origin: "Guinea",
    role: "Teacher and parent",
    route: "protection",
    filter: "protection",
    identity: "Travelling with her eight-year-old daughter",
    summary: "Mariam is asking for protection and must also navigate school and family needs.",
    stakes: "Every decision affects both her own safety and her daughter’s wellbeing.",
    tone: "plum",
  },
  {
    id: "sofia",
    name: "Sofía Quispe",
    initials: "SQ",
    pronouns: "she / her",
    origin: "Peru",
    role: "Healthcare assistant",
    route: "general",
    filter: "work",
    identity: "Recruited for a full-time care role",
    summary: "Sofía has a job offer, but a contract alone does not give permission to work.",
    stakes: "She needs to recognise fair recruitment, lawful deductions and workplace rights.",
    tone: "rose",
  },
  {
    id: "valentina",
    name: "Valentina Rojas",
    initials: "VR",
    pronouns: "she / her",
    origin: "Colombia",
    role: "Graphic designer",
    route: "protection",
    filter: "protection",
    identity: "A trans woman whose safety concerns are personal and specific",
    summary: "Valentina needs to explain why she personally fears persecution or serious harm.",
    stakes: "She must decide when and how to disclose sensitive information and ask for support.",
    tone: "violet",
  },
  {
    id: "noor",
    name: "Noor Haddad",
    initials: "NH",
    pronouns: "they / them",
    origin: "Lebanon",
    role: "Postgraduate student",
    route: "study",
    filter: "study",
    identity: "Queer and non-binary, beginning a community-development master’s",
    summary: "Noor has a college offer and is planning the financial, visa and housing steps.",
    stakes: "The course is real, but the cost of living is much higher than they expected.",
    tone: "teal",
  },
  {
    id: "river",
    name: "River Okafor",
    initials: "RO",
    pronouns: "they / she",
    origin: "South Africa",
    role: "Software engineer",
    route: "family",
    filter: "family",
    identity: "Gender-fluid and moving to live with an Irish spouse",
    summary: "River wants to understand the family route and what permission may allow after arrival.",
    stakes: "Their remote employer assumes they can keep working before Irish permission is registered.",
    tone: "amber",
  },
  {
    id: "adama",
    name: "Adama Sissoko",
    initials: "AS",
    pronouns: "she / her",
    origin: "Mali",
    role: "Tailor and single parent",
    route: "protection-access",
    filter: "protection",
    identity: "A Black woman, wheelchair user and mother travelling with her young son",
    summary: "Adama needs protection while navigating mobility, pain, parenting and accessible reception needs.",
    stakes: "An inaccessible room or missed assessment could affect her health, her case and her ability to care for her child.",
    tone: "copper",
  },
  {
    id: "elena",
    name: "Elena Petrova",
    initials: "EP",
    pronouns: "she / her",
    origin: "Bulgaria",
    role: "Hotel housekeeper",
    route: "eu-mobility",
    filter: "eu",
    identity: "An older Roma trans woman exercising EU free-movement rights",
    summary: "Elena can work in Ireland as an EU citizen but encounters overlapping racism, transphobia and age discrimination.",
    stakes: "Incorrect demands for a work permit and discriminatory refusals could block employment and housing despite her EU rights.",
    tone: "brick",
  },
  {
    id: "leila",
    name: "Leila Rahman",
    initials: "LR",
    pronouns: "she / her",
    origin: "Bangladesh",
    role: "Former accounts assistant",
    route: "family-safety",
    filter: "family",
    identity: "A bisexual migrant woman and mother whose permission is linked to an abusive spouse",
    summary: "Leila is isolated by language, financial control and fear that leaving will end her right to remain.",
    stakes: "Her immediate safety, children, documents, housing and independent immigration position are connected but require different supports.",
    tone: "indigo",
  },
];

const official = {
  permits: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/",
  critical: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/",
  general: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/",
  work: "https://www.irishimmigration.ie/coming-to-work-in-ireland/",
  register: "https://www.irishimmigration.ie/registering-your-immigration-permission/",
  family: "https://www.irishimmigration.ie/coming-to-join-family-in-ireland/",
  study: "https://www.irishimmigration.ie/coming-to-study-in-ireland/",
  ipo: "https://ipo.irishimmigration.ie/",
  ipas: "https://ipas.irishimmigration.ie/",
  refugeeCouncil: "https://www.irishrefugeecouncil.ie/get-help/information-hub/after-12-june-2026/",
  wrc: "https://www.workplacerelations.ie/en/what_you_should_know/coming_to_work_in_ireland/",
};

export const stepsByRoute: Record<RouteKey, Step[]> = {
  critical: [
    {
      stage: "Plan",
      eyebrow: "Four months before the move",
      title: "A strong offer is only the beginning",
      scene: "The contract has arrived. The employer says the role is in demand and asks for an immediate start.",
      question: "What should happen before flights or notice are arranged?",
      law: "A Critical Skills Employment Permit depends on the occupation, remuneration, contract and employer meeting the current statutory criteria.",
      plainLaw: "Check the real job, pay, contract and employer against today’s official rules before relying on the offer.",
      sourceLabel: "Critical Skills Employment Permit",
      sourceUrl: official.critical,
      choices: [
        { id: "verify", label: "Check the occupation, pay, contract and employer, then submit the correct permit application.", correct: true, feedback: "This protects the move from being built on an ineligible offer.", consequence: "The timeline becomes realistic and the job is tested against the current rules." },
        { id: "contract", label: "Treat the signed contract as permission to work.", feedback: "A contract and an employment permit perform different legal functions.", consequence: "Travel or resignation could happen before the necessary permission exists." },
        { id: "visitor", label: "Enter as a visitor and complete the permit after starting.", feedback: "Visitor status does not authorise ordinary employment.", consequence: "The job and immigration position could both be put at risk." },
      ],
    },
    {
      stage: "Prepare",
      eyebrow: "Documents and timing",
      title: "One approval does not replace every other step",
      scene: "The permit is granted. A friend says that means no other immigration check is necessary.",
      question: "What is the safer plan?",
      law: "An employment permit authorises specified employment. A visa-required national must also obtain the appropriate long-stay visa before travelling.",
      plainLaw: "Permit, visa, border permission and residence registration are separate stages.",
      sourceLabel: "Coming to work in Ireland",
      sourceUrl: official.work,
      choices: [
        { id: "sequence", label: "Check visa requirements, prepare evidence and keep each approval accessible for travel.", correct: true, feedback: "Correct. Each document answers a different question.", consequence: "The traveller can explain the purpose of the move at the border." },
        { id: "permitvisa", label: "Assume the employment permit is automatically a travel visa.", feedback: "That is not correct for visa-required nationals.", consequence: "Boarding or entry may be disrupted even though the permit is valid." },
        { id: "agent", label: "Give every original document to an unverified agent.", feedback: "Keep control of identity documents and verify anyone offering paid help.", consequence: "Losing access to original documents creates delay and exploitation risks." },
      ],
    },
    {
      stage: "Travel",
      eyebrow: "At the Irish border",
      title: "Be ready to explain the purpose of travel",
      scene: "The immigration officer asks where the traveller will stay and which employer is expecting them.",
      question: "What should they do?",
      law: "A visa permits travel to the border; an immigration officer decides entry. Supporting documents should show the genuine purpose and arrangements.",
      plainLaw: "Carry truthful, consistent evidence of the job, permission and first address.",
      sourceLabel: "Irish Immigration Service",
      sourceUrl: official.work,
      choices: [
        { id: "answer", label: "Answer truthfully and show the permit, visa if required, contract and accommodation details.", correct: true, feedback: "Clear, consistent evidence supports the stated purpose of travel.", consequence: "The officer can assess the work journey using the correct documents." },
        { id: "tourism", label: "Say it is only a holiday to avoid questions about work.", feedback: "The account should match the real purpose and documents.", consequence: "Conflicting information can cause serious difficulty at the border." },
        { id: "phone", label: "Rely entirely on a recruiter answering the phone.", feedback: "The traveller should understand and carry their own key information.", consequence: "If the recruiter is unavailable, the purpose of travel may be unclear." },
      ],
    },
    {
      stage: "Arrive",
      eyebrow: "The first 90 days",
      title: "Registration turns permission into evidence",
      scene: "Work has started, but housing searches and appointments make the first weeks difficult.",
      question: "Which task should remain on the plan?",
      law: "People from outside the EU, UK and Switzerland staying more than 90 days generally must register their Irish immigration permission.",
      plainLaw: "Arrange registration and keep the permission, address and employment details accurate.",
      sourceLabel: "Registering immigration permission",
      sourceUrl: official.register,
      choices: [
        { id: "register", label: "Arrange registration, follow the official appointment process and keep evidence of attempts.", correct: true, feedback: "The Irish Residence Permit records the permission and its conditions.", consequence: "The person has clearer evidence of lawful residence and what the permission allows." },
        { id: "pps", label: "Assume a PPS number replaces immigration registration.", feedback: "A PPS number is for public-service and tax interactions, not immigration permission.", consequence: "A useful administrative number would be mistaken for legal residence evidence." },
        { id: "contract", label: "Assume the employer’s contract replaces an IRP.", feedback: "Employment paperwork does not replace residence registration.", consequence: "The person may struggle to prove their immigration conditions." },
      ],
    },
    {
      stage: "Build a life",
      eyebrow: "Workplace and future",
      title: "Status does not cancel employment rights",
      scene: "A manager says migrant staff receive lower pay and fewer breaks during their first months.",
      question: "What response protects both work and immigration position?",
      law: "Migrant workers lawfully employed in Ireland have core employment protections. Permit conditions and employment rights must both be considered when problems arise.",
      plainLaw: "Keep records, seek reliable advice and do not accept unlawful treatment because of migrant status.",
      sourceLabel: "Workplace Relations Commission",
      sourceUrl: official.wrc,
      choices: [
        { id: "records", label: "Save rosters and payslips, ask for correction and contact the WRC or a qualified adviser.", correct: true, feedback: "Evidence and timely advice help protect both sets of rights.", consequence: "The concern can be addressed without pretending the permit conditions do not matter." },
        { id: "accept", label: "Accept it because permit holders have fewer employment rights.", feedback: "Immigration status does not remove core workplace protections.", consequence: "Underpayment or unsafe conditions may continue unchallenged." },
        { id: "disappear", label: "Leave immediately and begin another job without checking the permit conditions.", feedback: "Changing employment may require an official process or a new permit.", consequence: "A workplace problem could become an immigration problem too." },
      ],
    },
  ],
  general: [
    {
      stage: "Plan", eyebrow: "Before paying anyone", title: "Test the real job, not the sales pitch",
      scene: "A recruiter promises that any signed Irish contract guarantees a permit and asks for cash.",
      question: "What is the best first decision?",
      law: "A General Employment Permit depends on the occupation, remuneration, employer and other current requirements. Some occupations are ineligible and a Labour Market Needs Test may apply.",
      plainLaw: "Verify the employer and actual duties, then check the current permit rules before paying or travelling.", sourceLabel: "General Employment Permit", sourceUrl: official.general,
      choices: [
        { id: "check", label: "Verify the employer, duties, pay and permit eligibility through official sources.", correct: true, feedback: "A genuine offer still has to meet the legal criteria.", consequence: "Fraud and ineligible-job risks are identified before money or travel is committed." },
        { id: "cash", label: "Pay cash and let the recruiter keep the passport.", feedback: "Passport retention and pressure for untraceable payment are warning signs.", consequence: "The worker becomes more vulnerable to fraud and control." },
        { id: "promise", label: "Rely on the recruiter’s promise instead of checking the occupation.", feedback: "The official criteria, not a promise, decide permit eligibility.", consequence: "The planned route may fail after substantial expense." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "The correct order", title: "Permission must come before the move",
      scene: "The employer needs staff now and suggests entering as a tourist while paperwork catches up.",
      question: "Which sequence is reliable?",
      law: "A first employment-permit journey normally requires the permit before work begins, followed by a long-stay visa where required and registration after arrival.",
      plainLaw: "Do not use visitor status as a shortcut into ordinary employment.", sourceLabel: "Employment permits", sourceUrl: official.permits,
      choices: [
        { id: "order", label: "Permit first, visa if required, border control, then registration after arrival.", correct: true, feedback: "This keeps the journey aligned with the intended route.", consequence: "The worker arrives with an explainable and documented legal basis." },
        { id: "tourist", label: "Enter as a tourist and start on the first shift.", feedback: "Visitor status is not ordinary work permission.", consequence: "Both the worker and employer may face serious consequences." },
        { id: "pps", label: "Apply for a PPS number and treat it as the work permit.", feedback: "A PPS number does not create immigration or employment permission.", consequence: "The essential permit step remains unfinished." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Departure day", title: "Carry your own evidence",
      scene: "The recruiter says all documents are stored in the company office and the traveller needs only a phone screenshot.",
      question: "What should the traveller do?",
      law: "The traveller may need to demonstrate the purpose and conditions of the journey to the carrier and at Irish border control.",
      plainLaw: "Keep secure access to your passport, approvals, contract and first-address details.", sourceLabel: "Coming to work in Ireland", sourceUrl: official.work,
      choices: [
        { id: "copies", label: "Carry the originals required for travel plus secure copies and employer details.", correct: true, feedback: "The traveller should be able to explain their own journey.", consequence: "A missing phone signal or unavailable recruiter does not remove all evidence." },
        { id: "company", label: "Travel without documents because the company has them.", feedback: "Do not surrender control of essential identity and permission documents.", consequence: "The traveller may be unable to establish the purpose of travel." },
        { id: "different", label: "Give a different reason for travel from the one in the application.", feedback: "Information should be truthful and consistent.", consequence: "Contradictions may undermine the journey at the border." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "The first weeks", title: "Separate urgent needs from legal permissions",
      scene: "A bank, landlord and employer each ask for different documents while the registration appointment is pending.",
      question: "How should the person respond?",
      law: "An IRP records immigration permission. Other systems, including tax, banking and housing, have their own requirements and do not replace it.",
      plainLaw: "Use official checklists, keep appointment evidence and ask each service what it specifically requires.", sourceLabel: "Registering immigration permission", sourceUrl: official.register,
      choices: [
        { id: "organise", label: "Keep a document file, follow registration instructions and ask each service for its own checklist.", correct: true, feedback: "This reduces confusion between separate systems.", consequence: "Delays remain difficult, but the person can show what has been completed." },
        { id: "one", label: "Assume one document must work for every service.", feedback: "Irish systems ask different questions for different purposes.", consequence: "Applications may stall because the wrong evidence is repeatedly supplied." },
        { id: "fake", label: "Alter an address document to speed things up.", feedback: "Never submit false or altered evidence.", consequence: "A short-term shortcut creates serious legal and trust risks." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Fair work", title: "Spot exploitation early",
      scene: "The payslip contains unexplained deductions and the employer asks to hold the passport for ‘safe keeping’.",
      question: "What is the strongest response?",
      law: "Workers should receive lawful pay, terms and payslips. Keeping records and using the WRC or specialist migrant support can help address exploitation.",
      plainLaw: "Keep your passport, save evidence and seek confidential advice.", sourceLabel: "Workplace Relations Commission", sourceUrl: official.wrc,
      choices: [
        { id: "evidence", label: "Keep the passport, save records, request an explanation and contact the WRC or an adviser.", correct: true, feedback: "Clear records make it easier to understand and challenge the problem.", consequence: "The worker can seek help without relying only on the employer’s account." },
        { id: "hand", label: "Hand over the passport because the employer arranged the permit.", feedback: "The worker should retain control of personal identity documents.", consequence: "The employer gains a powerful means of control." },
        { id: "nothing", label: "Ignore deductions because migrant workers cannot complain.", feedback: "Migrant workers have enforceable employment rights.", consequence: "Unlawful treatment may continue or worsen." },
      ],
    },
  ],
  protection: [
    {
      stage: "Plan", eyebrow: "A need for safety", title: "Protection is about personal risk",
      scene: "Return feels unsafe. Friends offer conflicting advice and one person suggests inventing a stronger story.",
      question: "What principle should guide the next step?",
      law: "International protection is for people who fear persecution or face a real risk of serious harm. Each application is assessed on its individual facts under the law applying when it is made.",
      plainLaw: "Tell your own truthful story and get confidential legal information as early as possible.", sourceLabel: "Irish Refugee Council: applications after 12 June 2026", sourceUrl: official.refugeeCouncil,
      choices: [
        { id: "truth", label: "Keep personal evidence where safe, tell the truth and seek reliable legal information.", correct: true, feedback: "A protection claim must be the person’s own account.", consequence: "The case begins with accurate information and appropriate support." },
        { id: "copy", label: "Copy a story that worked for someone else.", feedback: "Invented or borrowed information can seriously damage credibility.", consequence: "The process may focus on contradictions rather than the real fear." },
        { id: "work", label: "Present protection as a faster employment route.", feedback: "Protection and labour migration have different purposes.", consequence: "The genuine legal basis of the journey is obscured." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Safety and evidence", title: "Documents help, but safety comes first",
      scene: "Some evidence is on a damaged phone. Other documents were impossible to bring.",
      question: "What is the responsible approach?",
      law: "Applicants should provide available information, cooperate with the process and explain missing evidence truthfully. Interpretation, vulnerability and accessibility needs should be raised.",
      plainLaw: "Do not invent missing documents. Explain what exists, what is missing and why.", sourceLabel: "International Protection Office", sourceUrl: official.ipo,
      choices: [
        { id: "explain", label: "Preserve what is safe, explain gaps and ask for an interpreter or accessibility support when needed.", correct: true, feedback: "The process should hear the person’s own account with appropriate support.", consequence: "Missing evidence is addressed openly rather than concealed." },
        { id: "forge", label: "Create replacement documents that look official.", feedback: "False documents can seriously harm a claim.", consequence: "Attention shifts away from the real circumstances and towards deception." },
        { id: "silence", label: "Never mention trauma, identity or disability even when relevant.", feedback: "Sensitive information can be discussed confidentially with qualified support.", consequence: "Important protection or procedural needs may remain unseen." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Reaching Ireland", title: "Say clearly that protection is needed",
      scene: "At an Irish port of entry, fear and exhaustion make it difficult to explain why return is unsafe.",
      question: "What should the person communicate?",
      law: "A person seeking asylum should clearly state that they want international protection and cooperate with the applicable registration and screening process.",
      plainLaw: "Use direct words: ‘I want to apply for international protection. I am afraid to return.’",
      sourceLabel: "International Protection Office", sourceUrl: official.ipo,
      choices: [
        { id: "ask", label: "Clearly ask for international protection and request interpretation if needed.", correct: true, feedback: "Clear communication helps direct the person into the correct process.", consequence: "The stated fear of return can be recorded and assessed." },
        { id: "tourist", label: "Hide the fear and say the visit is only tourism.", feedback: "That does not communicate the need for protection.", consequence: "The person may not enter the process intended to assess the risk." },
        { id: "script", label: "Repeat a memorised account that is not accurate.", feedback: "Use the person’s own truthful words.", consequence: "Inconsistencies may make an already difficult interview harder." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "The application and reception system", title: "IPO and IPAS have different roles",
      scene: "The applicant needs legal information, accommodation and help with a child’s school place.",
      question: "Which plan recognises the different responsibilities?",
      law: "The IPO examines protection applications. IPAS is responsible for reception accommodation and related supports. Legal Aid and independent organisations provide separate assistance.",
      plainLaw: "Case decision, accommodation and legal advice come from different services.", sourceLabel: "IPAS accommodation and supports", sourceUrl: official.ipas,
      choices: [
        { id: "roles", label: "Engage with IPO about the case, IPAS about reception needs and a lawyer about legal advice.", correct: true, feedback: "Separating the roles makes it easier to ask the right body for help.", consequence: "Urgent needs and the legal application can progress through the appropriate channels." },
        { id: "manager", label: "Ask an accommodation manager to approve refugee status.", feedback: "Accommodation staff do not decide the protection claim.", consequence: "Time is lost asking the wrong person for a legal decision." },
        { id: "address", label: "Move without updating the authorities or legal adviser.", feedback: "Contact information should be kept current.", consequence: "Important appointments or decisions could be missed." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Waiting and participating", title: "Check current rights instead of relying on rumours",
      scene: "An employer offers work, while other residents disagree about when applicants may enter the labour market.",
      question: "What should the applicant do?",
      law: "Labour-market access depends on the law, timing and conditions applying to the individual application. Education, health, complaints and child supports have separate rules.",
      plainLaw: "Check current eligibility and obtain the required permission before starting work.", sourceLabel: "Irish Refugee Council Information Hub", sourceUrl: official.refugeeCouncil,
      choices: [
        { id: "current", label: "Check the current rule for this application and start only after any required permission is granted.", correct: true, feedback: "This avoids applying an old rule or another person’s circumstances to the case.", consequence: "The job decision rests on current, individual information." },
        { id: "rumour", label: "Start because another resident was allowed to work.", feedback: "Another person may have applied under different rules or at a different time.", consequence: "The applicant may act without the permission their own case requires." },
        { id: "never", label: "Assume applicants can never study, work or raise concerns.", feedback: "Applicants have rights and routes to support, although conditions apply.", consequence: "Opportunities and protections may be missed unnecessarily." },
      ],
    },
  ],
  study: [
    {
      stage: "Plan", eyebrow: "Before accepting a place", title: "Check the course and the full cost",
      scene: "The college offer looks exciting, but the budget covers tuition and only six weeks of rent.",
      question: "What should be tested before committing?",
      law: "Study permission depends on the course, provider, finances, insurance and other current immigration requirements.",
      plainLaw: "Confirm the programme qualifies and make a realistic plan for fees, housing, insurance and daily life.", sourceLabel: "Coming to study in Ireland", sourceUrl: official.study,
      choices: [
        { id: "budget", label: "Verify the course and provider, then calculate tuition, housing, insurance and living costs.", correct: true, feedback: "Admission is only one part of a viable study journey.", consequence: "The student can judge whether the plan is financially and legally realistic." },
        { id: "job", label: "Assume a part-time job will cover every cost immediately.", feedback: "Work rights are limited by permission and employment is not guaranteed.", consequence: "The student may arrive without enough resources for basic needs." },
        { id: "deposit", label: "Pay an unverified agent before checking the programme.", feedback: "Verify the institution, programme and payment channel first.", consequence: "Fees may be lost on a course that does not support the intended permission." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Permission before departure", title: "Admission is not a visa",
      scene: "The acceptance email arrives and the student assumes it is the only document needed to travel.",
      question: "What is the correct next move?",
      law: "Visa-required students generally need the appropriate long-stay study visa. All students must be able to show the purpose and conditions of study.",
      plainLaw: "Follow the official student immigration checklist; a college offer does not replace travel permission.", sourceLabel: "Coming to study in Ireland", sourceUrl: official.study,
      choices: [
        { id: "visa", label: "Follow the official visa process if required and organise the financial, insurance and course evidence.", correct: true, feedback: "This connects the admission offer to the correct immigration route.", consequence: "Travel is supported by a complete and consistent study plan." },
        { id: "offer", label: "Use the acceptance email as an automatic visa.", feedback: "Admission and immigration permission are separate.", consequence: "Travel could fail before the course begins." },
        { id: "tourist", label: "Enter as a tourist and switch quietly after classes start.", feedback: "Use the correct study route before travel.", consequence: "The student may be unable to register the intended permission." },
      ],
    },
    {
      stage: "Travel", eyebrow: "At border control", title: "The study plan must make sense",
      scene: "The officer asks where the student will live, how the course is funded and when it begins.",
      question: "How should the student respond?",
      law: "Entry is assessed at the border. Documents and answers should demonstrate a genuine, prepared course of study.",
      plainLaw: "Carry truthful evidence of the course, finances, insurance and first accommodation.", sourceLabel: "Irish Immigration Service", sourceUrl: official.study,
      choices: [
        { id: "show", label: "Answer truthfully and show the course, payment, insurance, finance and accommodation evidence.", correct: true, feedback: "The documents support the stated study purpose.", consequence: "The officer can understand the plan without relying on assumptions." },
        { id: "work", label: "Say the main purpose is full-time work.", feedback: "That conflicts with a study application.", consequence: "The purpose of travel appears inconsistent." },
        { id: "guess", label: "Guess the college address and course dates.", feedback: "Students should know the basic details of their own programme.", consequence: "The study plan may not appear genuine or prepared." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "The first term", title: "Register and keep the course active",
      scene: "Housing problems make it tempting to postpone registration and miss classes.",
      question: "Which response best protects the study journey?",
      law: "Eligible non-EEA students staying more than 90 days must register their permission and continue meeting the attendance and course conditions attached to it.",
      plainLaw: "Register, stay engaged with the course and tell the college early when serious problems affect attendance.", sourceLabel: "Registering immigration permission", sourceUrl: official.register,
      choices: [
        { id: "support", label: "Arrange registration, attend the course and contact student support early about housing or wellbeing.", correct: true, feedback: "Immigration and academic responsibilities are easier to protect with early support.", consequence: "Problems are recorded before they become unexplained absence or loss of status." },
        { id: "skip", label: "Stop attending without telling the college.", feedback: "Course engagement is important to the permission.", consequence: "Academic and immigration consequences may compound the housing problem." },
        { id: "pps", label: "Use a PPS number instead of registration.", feedback: "A PPS number is not study permission.", consequence: "The required residence-registration step remains incomplete." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Work, community and next steps", title: "Student work has boundaries",
      scene: "An employer offers full-time hours during term and says nobody checks student conditions.",
      question: "What should the student do?",
      law: "A student’s right to work depends on the stamp and current conditions. Exceeding those conditions can affect immigration status and study.",
      plainLaw: "Check the hours and dates allowed by the current student permission before accepting a roster.", sourceLabel: "Immigration permission stamps", sourceUrl: "https://www.irishimmigration.ie/registering-your-immigration-permission/information-on-registering/immigration-permission-stamps/",
      choices: [
        { id: "limits", label: "Check the current Stamp 2 conditions and accept only work that fits them.", correct: true, feedback: "Permission conditions matter even when an employer offers more hours.", consequence: "Employment supports the student rather than undermining the course and status." },
        { id: "full", label: "Take unrestricted hours because the employer approved them.", feedback: "An employer cannot enlarge immigration permission.", consequence: "The student may breach the conditions of stay." },
        { id: "cash", label: "Work off the books so the hours are invisible.", feedback: "Undeclared work creates employment, tax and immigration risks.", consequence: "The student loses important workplace protections and creates further risk." },
      ],
    },
  ],
  family: [
    {
      stage: "Plan", eyebrow: "Before the move", title: "The sponsor determines the route",
      scene: "A spouse in Ireland believes marriage automatically gives the same rights as Irish citizenship.",
      question: "What needs to be established first?",
      law: "Family routes differ depending on whether the sponsor is Irish, UK, EEA or Swiss, non-EEA, or a beneficiary of international protection.",
      plainLaw: "Identify the sponsor’s exact status and the relationship category before choosing a form or visa.", sourceLabel: "Coming to join family in Ireland", sourceUrl: official.family,
      choices: [
        { id: "sponsor", label: "Check the sponsor’s status, the relationship category and the current financial and document rules.", correct: true, feedback: "That identifies the correct family route.", consequence: "The application is built for the actual sponsor and relationship." },
        { id: "marriage", label: "Assume a marriage certificate grants automatic entry and work rights.", feedback: "The relationship evidence is important, but an immigration process still applies.", consequence: "Travel or work may be attempted without the required permission." },
        { id: "form", label: "Use the first family form found online, regardless of sponsor status.", feedback: "Different sponsors and family members follow different processes.", consequence: "The wrong application can cause avoidable delay or refusal." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Evidence and permission", title: "Show a genuine family plan",
      scene: "The couple has years of messages and visits, but their housing and financial evidence is disorganised.",
      question: "What is the best preparation?",
      law: "Family applications may examine the qualifying relationship, sponsor eligibility, finances, accommodation, dependency and other route-specific criteria.",
      plainLaw: "Use the official checklist and organise truthful evidence of the relationship and practical plan.", sourceLabel: "Join family guidance", sourceUrl: official.family,
      choices: [
        { id: "file", label: "Build a clear evidence file using the checklist and explain any genuine gaps.", correct: true, feedback: "Organised, truthful evidence makes the application easier to assess.", consequence: "The family’s real history and plan are visible without manufactured material." },
        { id: "fake", label: "Create documents for periods when little evidence exists.", feedback: "False evidence can seriously damage the application.", consequence: "Trust in the whole application may be undermined." },
        { id: "ignore", label: "Ignore financial or housing requirements because the relationship is genuine.", feedback: "A genuine relationship does not remove every route condition.", consequence: "A preventable evidence gap may delay or defeat the application." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Arrival as a family member", title: "State the real purpose at the border",
      scene: "The traveller has the relevant visa or preclearance and plans to live with the sponsor.",
      question: "What should happen at entry?",
      law: "Where a visa or preclearance is required, it supports travel for the stated family purpose. Entry and the initial permission are considered at the border.",
      plainLaw: "Explain the family purpose honestly and carry the approval and sponsor details.", sourceLabel: "Coming to join family", sourceUrl: official.family,
      choices: [
        { id: "family", label: "State the family purpose and show the approval, relationship and sponsor-address details.", correct: true, feedback: "The explanation matches the application and documents.", consequence: "The officer can assess entry on the intended family basis." },
        { id: "holiday", label: "Say it is only a short holiday despite plans to remain.", feedback: "The stated purpose should be truthful.", consequence: "The account conflicts with the family application and intended stay." },
        { id: "none", label: "Carry no sponsor contact or accommodation information.", feedback: "Basic evidence of the family and arrival plan should be accessible.", consequence: "The traveller may struggle to explain where and with whom they will live." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "Registration and conditions", title: "Do not guess what the stamp allows",
      scene: "A remote employer wants the family member to resume work immediately from an Irish address.",
      question: "What should the person do before working?",
      law: "The right to work depends on the immigration permission granted. Family permissions can differ according to the sponsor and route.",
      plainLaw: "Register the permission where required and confirm its work conditions before starting or resuming employment in Ireland.", sourceLabel: "Immigration permission stamps", sourceUrl: "https://www.irishimmigration.ie/registering-your-immigration-permission/information-on-registering/immigration-permission-stamps/",
      choices: [
        { id: "stamp", label: "Complete the required registration and check exactly what the permission permits.", correct: true, feedback: "The stamp or IRP conditions answer the work question.", consequence: "Employment begins only when the Irish permission supports it." },
        { id: "spouse", label: "Assume every spouse automatically has unrestricted work rights.", feedback: "Family permissions are not all identical.", consequence: "Work may begin before the necessary condition is satisfied." },
        { id: "remote", label: "Assume foreign remote work is outside Irish immigration conditions.", feedback: "Working while physically in Ireland can still engage Irish immigration, tax and employment rules.", consequence: "A remote arrangement creates unexpected legal and tax issues." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Independence and belonging", title: "Build support beyond the sponsor",
      scene: "The move feels isolating, and the family member depends on the sponsor for every document, appointment and social contact.",
      question: "Which step creates greater security?",
      law: "Migrants can seek independent information about immigration, work, health, safety and local services. Emergency and specialist supports remain available when relationships become unsafe.",
      plainLaw: "Keep copies of your own documents and learn how to reach independent services.", sourceLabel: "Irish Immigration Service", sourceUrl: official.family,
      choices: [
        { id: "network", label: "Keep personal document copies and connect with independent advice, community and health services.", correct: true, feedback: "A wider support network improves practical independence and safety.", consequence: "The person can make informed decisions without relying on one relationship for everything." },
        { id: "all", label: "Let the sponsor keep every document and password.", feedback: "Adults should retain safe access to their own identity and account information.", consequence: "Every practical decision becomes dependent on the sponsor." },
        { id: "silent", label: "Avoid support because asking questions might affect status.", feedback: "Reliable, confidential information helps people understand their options.", consequence: "Problems may become more serious before help is sought." },
      ],
    },
  ],
  "protection-access": [
    {
      stage: "Plan", eyebrow: "Safety, disability and parenting", title: "Protection and accessibility are separate questions",
      scene: "Adama is told that using a wheelchair will either guarantee protection or prevent her from applying with her son.",
      question: "What should guide her decision?",
      law: "A protection claim is assessed on the individual risk of persecution or serious harm. Disability and single parenthood may create special reception or procedural needs, but do not by themselves decide the claim.",
      plainLaw: "Explain the real fear of return and separately identify the support needed to participate safely in the process.",
      sourceLabel: "Irish Refugee Council: applications after 12 June 2026", sourceUrl: official.refugeeCouncil,
      choices: [
        { id: "separate", label: "Explain the protection risk truthfully and make a separate list of mobility, health and parenting needs.", correct: true, feedback: "This keeps the legal claim and access needs both visible.", consequence: "Decision-makers receive the protection account while reception staff can identify practical support." },
        { id: "guarantee", label: "Assume disability automatically guarantees refugee status.", feedback: "Vulnerability and the legal test for protection are not the same.", consequence: "The personal fear of return may not be properly explained." },
        { id: "hide", label: "Hide the disability because parents with support needs cannot apply.", feedback: "Disability does not remove the right to seek protection.", consequence: "Necessary reception and procedural supports may be missed." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Screening and vulnerability", title: "Name every need, not only the most visible one",
      scene: "The wheelchair is obvious, but chronic pain, trauma, medication and caring for a six-year-old are not.",
      question: "How should Adama approach the vulnerability assessment?",
      law: "Under the 2026 system, applicants are offered a voluntary vulnerability assessment. Disability, single parenthood, serious illness and experiences of violence are among the recognised categories used to identify special reception needs.",
      plainLaw: "Use the assessment to explain hidden as well as visible needs and ask for the information to be recorded accurately.",
      sourceLabel: "IPAS vulnerability assessment", sourceUrl: "https://ipas.irishimmigration.ie/accommodation/securing-accommodation/",
      choices: [
        { id: "full", label: "Describe mobility, pain, medication, trauma and parenting needs, using interpretation if required.", correct: true, feedback: "Overlapping needs can require different practical responses.", consequence: "The assessment contains a fuller basis for accommodation and service referrals." },
        { id: "chair", label: "Mention only the wheelchair because everything else is private.", feedback: "She controls disclosure, but unrecorded needs may be harder to accommodate.", consequence: "Pain, medication or parenting barriers may remain invisible until a crisis." },
        { id: "refuse", label: "Refuse because accepting an assessment weakens the protection claim.", feedback: "The assessment is voluntary and addresses support needs rather than deciding protection status.", consequence: "A route to identifying special reception needs is lost for the wrong reason." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Moving through the reception system", title: "An offered bed may still be unusable",
      scene: "Transport is arranged to accommodation, but Adama learns that her room is upstairs and the bathroom cannot be used safely.",
      question: "What response creates the clearest record?",
      law: "IPAS uses vulnerability information to address special reception needs. Medical-priority or exceptional transfer and additional-consideration processes exist, although a preferred location or immediate transfer is not guaranteed.",
      plainLaw: "Describe the exact access barrier in writing, provide available medical evidence and use the official escalation process.",
      sourceLabel: "IPAS accommodation and medical consideration", sourceUrl: "https://ipas.irishimmigration.ie/accommodation/securing-accommodation/",
      choices: [
        { id: "record", label: "Report the precise barrier immediately, keep copies and request medical or exceptional consideration through IPAS.", correct: true, feedback: "Specific written evidence is stronger than a general request to move.", consequence: "IPAS can assess the actual safety and access problem through the relevant process." },
        { id: "leave", label: "Leave without telling anyone and assume another room will appear.", feedback: "Leaving can disconnect her from reception support without solving the barrier.", consequence: "Adama and her child may face homelessness and become harder to contact." },
        { id: "accept", label: "Use the unsafe room because residents cannot challenge suitability.", feedback: "Accommodation concerns and special needs can be raised.", consequence: "Falls, missed hygiene and worsening pain become more likely." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "Interview access", title: "Participation may require adjustments",
      scene: "An interview venue, long sitting time and medication side effects could prevent Adama from giving a complete account.",
      question: "What should she do before the appointment?",
      law: "Applicants should attend and cooperate with the process, while raising disability, communication, health and other procedural needs as early as possible. Specialist legal advice can help explain relevant accommodations and deadlines.",
      plainLaw: "Tell the IPO and legal adviser what makes participation difficult before the interview, not only after it fails.",
      sourceLabel: "Irish Refugee Council Independent Law Centre", sourceUrl: "https://www.irishrefugeecouncil.ie/get-help/services-support/law-centre/",
      choices: [
        { id: "early", label: "Contact the IPO and legal adviser early with specific access, break, medication and childcare concerns.", correct: true, feedback: "Specific advance notice gives the process a chance to respond.", consequence: "Adama is better able to participate and her son’s care can be planned." },
        { id: "miss", label: "Miss the interview without contact because disability automatically excuses absence.", feedback: "Do not assume an absence will explain itself.", consequence: "A crucial procedural step may be missed without the reason being understood." },
        { id: "endure", label: "Say nothing and continue even when pain affects concentration.", feedback: "Unexplained difficulty may affect how the account is heard and recorded.", consequence: "Important details may be omitted or appear inconsistent." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Health, school and independence", title: "One appointment cannot solve every barrier",
      scene: "Adama needs a GP, medication continuity, a school place, accessible transport and information about work eligibility.",
      question: "What is the most realistic plan?",
      law: "Healthcare, education, reception accommodation and labour-market access operate through different Irish services and eligibility rules. IPAS publishes separate pathways and support information for each.",
      plainLaw: "Create a separate action and contact for health, school, accommodation and immigration rather than waiting for one service to manage everything.",
      sourceLabel: "IPAS services and supports", sourceUrl: "https://ipas.irishimmigration.ie/",
      choices: [
        { id: "plan", label: "Make a four-part plan and seek an advocate or support worker to coordinate urgent tasks.", correct: true, feedback: "Coordination matters because each system has a different role.", consequence: "Medication and school can be prioritised without losing track of accommodation or case duties." },
        { id: "ipo", label: "Ask the IPO caseworker to arrange every health, school and transport service.", feedback: "The IPO examines the protection application; it does not run all arrival services.", consequence: "Urgent practical needs are directed to the wrong body." },
        { id: "wait", label: "Wait for protection status before seeking healthcare or a school place.", feedback: "Applicants and children can access services while a case is pending, subject to the relevant rules.", consequence: "Health deteriorates and the child loses education time unnecessarily." },
      ],
    },
  ],
  "eu-mobility": [
    {
      stage: "Plan", eyebrow: "EU free movement", title: "Elena does not need an employment permit",
      scene: "A recruiter tells Elena that Bulgarian citizens need the same work permit as non-EEA workers and offers to sell one.",
      question: "What should she verify?",
      law: "As an EU citizen, Elena can enter Ireland with a valid passport or national identity card and can work without an Irish employment permit. Conditions apply to residence beyond the initial period.",
      plainLaw: "Do not pay for a work permit an EU citizen does not need; check the separate rules for staying longer term.",
      sourceLabel: "Coming from the EU/EEA to work", sourceUrl: "https://www.citizensinformation.ie/en/moving-country/working-in-ireland/migrant-workers/coming-from-eu-to-work/",
      choices: [
        { id: "eu", label: "Reject the permit sale, verify the employer and use official EU residence information.", correct: true, feedback: "Her EU citizenship changes the immigration route, not her need for a genuine job.", consequence: "Elena avoids a scam and plans around her real free-movement rights." },
        { id: "buy", label: "Pay because age and Roma ethnicity create a special permit requirement.", feedback: "Those identities do not create an employment-permit requirement for an EU citizen.", consequence: "Money and sensitive documents are handed to a dishonest recruiter." },
        { id: "visitor", label: "Hide the plan to work because EU citizens may only visit.", feedback: "EU citizens have a right to work in another EU state, subject to applicable residence rules.", consequence: "Elena misunderstands and underuses the legal basis she actually has." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Staying beyond the first months", title: "Free movement still has residence conditions",
      scene: "Elena plans to remain indefinitely but has only a short casual-work promise and almost no savings.",
      question: "Which plan is most reliable?",
      law: "EU citizens can initially reside in Ireland and may remain longer when exercising an EU Treaty right, such as working, self-employment, qualifying study or self-sufficiency. Jobseekers have specific protections and conditions.",
      plainLaw: "Keep evidence of genuine work or job-seeking and understand which basis supports residence after the initial period.",
      sourceLabel: "Residence rights of EU citizens in Ireland", sourceUrl: "https://www.citizensinformation.ie/en/moving-country/moving-to-ireland/rights-of-residence-in-ireland/residence-rights-eu-national/",
      choices: [
        { id: "evidence", label: "Keep job applications, contracts, payslips and housing records while checking the applicable residence basis.", correct: true, feedback: "Evidence helps show that Elena is working or genuinely seeking work.", consequence: "Her longer-term plan rests on a documented Treaty-right basis." },
        { id: "forever", label: "Assume EU citizenship creates unconditional permanent residence from day one.", feedback: "Initial entry and longer-term residence are not identical.", consequence: "Elena may discover a residence issue only when trying to access another service." },
        { id: "cash", label: "Accept undocumented cash work because any work proves residence.", feedback: "Undeclared work weakens employment protections and may not provide usable evidence.", consequence: "Exploitation grows while her work history remains difficult to prove." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Starting work", title: "A PPS number and an IRP are not EU work permits",
      scene: "The hotel asks Elena for an Irish Residence Permit before it will put her on the roster.",
      question: "How should she respond?",
      law: "EU citizens do not generally register with Immigration Service Delivery or obtain an IRP to exercise their own EU rights. A PPS number is a separate identifier for tax and public-service purposes.",
      plainLaw: "Show EU identity and explain the correct right-to-work basis; complete tax and PPS steps separately.",
      sourceLabel: "EU citizens working in Ireland", sourceUrl: "https://www.citizensinformation.ie/en/moving-country/working-in-ireland/migrant-workers/coming-from-eu-to-work/",
      choices: [
        { id: "explain", label: "Provide her Bulgarian identity document and ask HR to review the EU-worker rules.", correct: true, feedback: "This corrects the requirement without inventing a document she should not hold.", consequence: "The employer can onboard her on the proper EU basis." },
        { id: "fake", label: "Buy a false IRP because the employer insists.", feedback: "Never create or buy false immigration documents.", consequence: "An employer error becomes a serious legal problem for Elena." },
        { id: "ppswork", label: "Say a PPS number is the document that grants EU work rights.", feedback: "The PPS number does not create the right to work.", consequence: "Two separate systems remain confused." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "Housing discrimination", title: "A refusal may involve more than affordability",
      scene: "A landlord is positive on the phone, then says the room is unavailable after seeing Elena and hearing that she is Roma and trans.",
      question: "What can Elena do without assuming every refusal is unlawful?",
      law: "Irish equality law prohibits housing discrimination on protected grounds including race, gender and age. Transgender discrimination is protected under the gender ground, but evidence and time limits matter in a complaint.",
      plainLaw: "Record what happened, save the advertisement and messages, and seek prompt housing or equality advice.",
      sourceLabel: "IHREC: race and housing", sourceUrl: "https://www.ihrec.ie/your-rights/race/housing",
      choices: [
        { id: "save", label: "Save the listing and messages, write down what was said and seek advice from IHREC or a housing service.", correct: true, feedback: "Contemporaneous evidence helps distinguish discrimination from another explanation.", consequence: "Elena can assess a complaint while continuing the urgent housing search." },
        { id: "threat", label: "Threaten the landlord publicly without preserving any evidence.", feedback: "Anger is understandable, but evidence and advice create a stronger route to remedy.", consequence: "The listing disappears and the exact discriminatory words become harder to prove." },
        { id: "accept", label: "Assume discrimination against Roma or trans renters is legal in a private property.", feedback: "Private housing services are covered by equality rules, subject to legal details and exceptions.", consequence: "A potentially actionable refusal goes unexamined." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "Workplace equality", title: "One incident can sit on several protected grounds",
      scene: "A supervisor mocks Elena’s accent and gender, gives younger non-Roma workers better shifts and tells her to use a different name badge.",
      question: "What response protects the overlapping issues?",
      law: "The Employment Equality Acts prohibit workplace discrimination on grounds including gender, race and age. Trans discrimination is protected under the gender ground; workplace complaints can be brought to the WRC.",
      plainLaw: "Record each incident and comparator, use the employer process where safe, and get equality advice promptly.",
      sourceLabel: "IHREC workplace discrimination", sourceUrl: "https://www.ihrec.ie/factsheets/discrimination-against-workers-recruitment-and-promotion",
      choices: [
        { id: "log", label: "Keep a dated record of words, shifts and witnesses, then seek IHREC or WRC guidance.", correct: true, feedback: "The record shows how race, gender and age may operate together.", consequence: "Elena can pursue an informed internal or external remedy before evidence and deadlines are lost." },
        { id: "one", label: "Report only age because one complaint cannot involve overlapping grounds.", feedback: "A complaint can describe more than one protected ground where the facts support it.", consequence: "The racial and gender aspects of the treatment disappear from the account." },
        { id: "quit", label: "Quit immediately without saving rosters, messages or seeking advice.", feedback: "Safety comes first, but preserving evidence and advice can protect later options.", consequence: "Income stops and the pattern becomes harder to demonstrate." },
      ],
    },
  ],
  "family-safety": [
    {
      stage: "Plan", eyebrow: "Immediate safety", title: "Immigration fear can be part of coercive control",
      scene: "Leila’s spouse controls her passport, money and phone and says Gardaí will deport her if she leaves with the children.",
      question: "What should come first?",
      law: "Domestic abuse can include coercive control as well as physical violence. Anyone in immediate danger should contact 999 or 112; immigration status does not prevent a victim from contacting An Garda Síochána or a specialist service.",
      plainLaw: "Prioritise immediate safety and confidential specialist help; the abuser does not decide immigration status.",
      sourceLabel: "Women’s Aid support", sourceUrl: "https://www.womensaid.ie/get-help/",
      choices: [
        { id: "safe", label: "Use a safe device or trusted contact to reach emergency or specialist domestic-abuse support.", correct: true, feedback: "Safety planning can account for children, language, monitoring and documents.", consequence: "Leila receives confidential options without first having to confront the abuser." },
        { id: "confront", label: "Announce the plan to leave and demand every document back while alone.", feedback: "Confrontation can increase danger; a specialist can help plan a safer exit.", consequence: "The abuser may escalate violence or remove documents and money." },
        { id: "believe", label: "Stay because the spouse has legal power to order deportation.", feedback: "A spouse does not make immigration decisions.", consequence: "False immigration threats continue to trap Leila and the children." },
      ],
    },
    {
      stage: "Prepare", eyebrow: "Private communication", title: "A safe contact method matters",
      scene: "The spouse checks browser history and translates every official letter before Leila can read it.",
      question: "How can she seek information more safely?",
      law: "ISD warns that devices leave digital traces and permits a victim to use a representative contact. Women’s Aid can access an interpreter and connect callers with services around Ireland.",
      plainLaw: "Use a safer device and contact details the abuser cannot monitor; ask for an interpreter rather than relying on the abuser.",
      sourceLabel: "ISD domestic-abuse immigration guidelines", sourceUrl: "https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/immigration-guidelines-for-victims-of-domestic-abuse/",
      choices: [
        { id: "private", label: "Use a trusted device, safe email or representative address and request independent interpretation.", correct: true, feedback: "This reduces monitoring and gives Leila direct access to her own information.", consequence: "Support services can communicate without routing everything through the spouse." },
        { id: "shared", label: "Use the shared family account because deleting history removes every trace.", feedback: "Deleting history does not guarantee that activity is hidden.", consequence: "The spouse may discover the safety or immigration plan." },
        { id: "translate", label: "Let the spouse translate every confidential conversation.", feedback: "An alleged abuser should not control interpretation of safety or legal advice.", consequence: "Information may be changed, withheld or used to intimidate Leila." },
      ],
    },
    {
      stage: "Travel", eyebrow: "Independent immigration status", title: "Leaving does not automatically end permission",
      scene: "Leila’s residence permission is linked to her spouse, and she believes moving to a refuge will make her unlawful that night.",
      question: "What route should she investigate urgently?",
      law: "A victim whose permission is linked to the perpetrator may apply directly or through a solicitor for independent immigration permission under the ISD domestic-abuse guidelines. There is no application fee and the application is treated confidentially.",
      plainLaw: "Get advice about the independent-permission process; leaving the abuser and losing status are not automatically the same event.",
      sourceLabel: "Independent permission for victims of domestic abuse", sourceUrl: "https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/immigration-guidelines-for-victims-of-domestic-abuse/",
      choices: [
        { id: "apply", label: "Contact ISD or a solicitor through safe channels and request independent status under the guidelines.", correct: true, feedback: "The scheme exists for permission linked to the alleged perpetrator.", consequence: "ISD can assess Leila’s own circumstances without the spouse controlling the application." },
        { id: "permission", label: "Ask the spouse to sign permission for her independent application.", feedback: "The perpetrator has no decision-making role in the independent-status request.", consequence: "The spouse is alerted and gains another opportunity to obstruct safety." },
        { id: "automatic", label: "Assume moving to a refuge automatically grants Stamp 4.", feedback: "Independent permission requires an application and assessment; it is not automatic.", consequence: "Leila may believe the immigration step is complete when it is not." },
      ],
    },
    {
      stage: "Arrive", eyebrow: "Evidence without perfection", title: "Not every survivor has a Garda report",
      scene: "Most abuse happened at home. Leila has messages and a GP visit but no court order or Garda incident number.",
      question: "How should she build the application?",
      law: "ISD asks for as much information as possible and lists examples including court orders, medical or Garda reports, State-body letters and domestic-violence service letters. The circumstances and children should be explained; the examples are not a reason to fabricate evidence.",
      plainLaw: "Collect what genuinely exists, explain gaps and ask a solicitor or support service to help present the history.",
      sourceLabel: "ISD evidence guidance", sourceUrl: "https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/immigration-guidelines-for-victims-of-domestic-abuse/",
      choices: [
        { id: "genuine", label: "Preserve genuine messages and records, describe the pattern and seek supporting letters where appropriate.", correct: true, feedback: "A coherent truthful account can draw on different forms of evidence.", consequence: "ISD receives the available history without a false document undermining it." },
        { id: "wait", label: "Wait to seek help until she has every example on the ISD list.", feedback: "Safety and advice should not be postponed in pursuit of a perfect file.", consequence: "Danger continues and useful evidence may be lost." },
        { id: "create", label: "Create a Garda report number because official evidence is always required.", feedback: "Never invent evidence.", consequence: "False information may damage both credibility and the immigration application." },
      ],
    },
    {
      stage: "Build a life", eyebrow: "After immediate safety", title: "Immigration permission is one part of recovery",
      scene: "Leila needs income, secure housing, school continuity and LGBT-affirming support while family-law questions remain unresolved.",
      question: "What is the most realistic next step?",
      law: "If independent permission is approved under the guidelines, Stamp 4 permits work without an employment permit. Safety, housing, child and family-law needs still require separate specialist services; refusal reasons and other immigration options should be explained if an application is refused.",
      plainLaw: "Build a coordinated plan for immigration, safety, children, housing and income rather than expecting one decision to solve everything.",
      sourceLabel: "ISD domestic-abuse immigration guidelines", sourceUrl: "https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/immigration-guidelines-for-victims-of-domestic-abuse/",
      choices: [
        { id: "team", label: "Use an immigration adviser, domestic-abuse service and appropriate family, housing and LGBT supports together.", correct: true, feedback: "Different specialists can address connected but legally distinct needs.", consequence: "Leila can rebuild independence without one service overlooking the children or another overlooking status." },
        { id: "stamp", label: "Assume Stamp 4 automatically provides housing and resolves child arrangements.", feedback: "Immigration permission does not decide housing or family-law issues.", consequence: "Urgent practical and legal needs remain unattended." },
        { id: "return", label: "Return to the spouse because approval is not guaranteed.", feedback: "Uncertainty deserves specialist planning, not forced exposure to danger.", consequence: "Coercive control resumes before independent options are properly assessed." },
      ],
    },
  ],
};

export const routeMeta = {
  critical: { label: "Critical Skills Employment Permit", short: "Skilled work", family: "work" as const },
  general: { label: "General Employment Permit", short: "Employment", family: "work" as const },
  protection: { label: "International protection", short: "Protection", family: "protection" as const },
  study: { label: "Long-stay study", short: "Study", family: "study" as const },
  family: { label: "Join family", short: "Family", family: "family" as const },
  "protection-access": { label: "Protection with accessibility needs", short: "Protection + access", family: "protection" as const },
  "eu-mobility": { label: "EU free movement", short: "EU mobility", family: "eu" as const },
  "family-safety": { label: "Independent permission after domestic abuse", short: "Family + safety", family: "family" as const },
};

export const routeFilters: { id: RouteFilter; label: string; description: string }[] = [
  { id: "all", label: "Show everyone", description: "Compare all twelve fictional journeys." },
  { id: "work", label: "I want to work", description: "Employment-permit journeys." },
  { id: "study", label: "I want to study", description: "Course, visa, finance and Stamp 2 decisions." },
  { id: "family", label: "I want to join family", description: "Sponsor, relationship and permission decisions." },
  { id: "protection", label: "I need safety", description: "International-protection and reception decisions." },
  { id: "eu", label: "I am an EU citizen", description: "Free-movement, work and equality decisions." },
];
